FROM alpine:latest

# "/bin/sh", "-c", "while true; do echo 'HTTP/1.1 200 OK\n\nHello World!' | nc -l -p 80; done"

CMD ["/bin/sh", "-c", "while true; do echo 'HTTP/1.1 200 OK\n\nHello World!' | nc -l -p 80; done"]
#RUN while true; do echo 'HTTP/1.1 200 OK\n\nHello World!' | nc -l -p 80; done

EXPOSE 80
